// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504085957_UpdateHikvisionCameraDescriptions")]
    partial class UpdateHikvisionCameraDescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aperture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FovDiagonal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FovHorizontal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FovVertical")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LensSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LensType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingTemp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aperture = "F1.4",
                            Brand = "HikVision",
                            Description = "Camera Bullet 8MP V-Focus HikVision",
                            FovDiagonal = "133°–53°",
                            FovHorizontal = "112°–46°",
                            FovVertical = "60°–26°",
                            IrRange = "50m",
                            LensSize = "Varifocal",
                            LensType = "Motorised Varifocal",
                            ModelNumber = "DS-2CD2685G1-IZS",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$480–$650",
                            Range = "50m",
                            Resolution = "8MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 2,
                            Aperture = "F1.4",
                            Brand = "HikVision",
                            Description = "Camera - 4MP Mini Bullet 4MP Bullet 40m IR IP67 2.8mm HIKVision",
                            FovDiagonal = "123°–98°–62°",
                            FovHorizontal = "103°–83°–53°",
                            FovVertical = "55°–45°–28°",
                            IrRange = "40m",
                            LensSize = "2.8mm",
                            LensType = "Fixed Focal Lens",
                            ModelNumber = "DS-2CD2046G2-I",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$180–$260",
                            Range = "40m",
                            Resolution = "4MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 3,
                            Aperture = "F2.0",
                            Brand = "HikVision",
                            Description = "Camera Bullet Single 2MP 30m WiFi IR IP66 2.8mm t/s CCTV c/w Power Adaptor I01213",
                            FovDiagonal = "135°–102°",
                            FovHorizontal = "114°–86°",
                            FovVertical = "62°–46°",
                            IrRange = "30m",
                            LensSize = "2.8mm",
                            LensType = "Fixed Focal Lens",
                            ModelNumber = "DS-2CD2021G1-IDW1",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$120–$180",
                            Range = "30m",
                            Resolution = "2MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 4,
                            Aperture = "F1.6",
                            Brand = "HikVision",
                            Description = "Camera Bullet 6MP 50m IR 2.8mm EXIR H.26 120dB WDR IP67",
                            FovDiagonal = "128°–101°",
                            FovHorizontal = "99°–80°–60°",
                            FovVertical = "61°–51°–38°",
                            IrRange = "80m",
                            LensSize = "2.8mm",
                            LensType = "Fixed Focal Lens",
                            ModelNumber = "DS-2CD2T65G1-I8",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$260–$340",
                            Range = "50m",
                            Resolution = "6MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 5,
                            Aperture = "F1.4",
                            Brand = "HikVision",
                            Description = "Camera - HIKVision 4K AcuSense Strobe Light Audible Warning Varifocal Bullet Netwok",
                            FovDiagonal = "127.4°–52°",
                            FovHorizontal = "108°–46°",
                            FovVertical = "58°–26°",
                            IrRange = "60m",
                            LensSize = "Varifocal",
                            LensType = "Motorised Varifocal",
                            ModelNumber = "DS-2CD2686G2-IZSU/SL",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$590–$750",
                            Range = "60",
                            Resolution = "8MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 6,
                            Aperture = "F1.4",
                            Brand = "HikVision",
                            Description = "Camera - Hikvision 4MP Deepin View ANPR Moto VF Bullet 8-32m iDS-(8-32mm)",
                            FovDiagonal = "127°–52°",
                            FovHorizontal = "108°–46°",
                            FovVertical = "58°–26°",
                            IrRange = "80m",
                            LensSize = "8-32mm",
                            LensType = "Motorised Varifocal",
                            ModelNumber = "IDS-2CD7A46G0/P-IZHS",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$650–$850",
                            Range = "8-32m",
                            Resolution = "4MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 7,
                            Aperture = "F1.5",
                            Brand = "HikVision",
                            Description = "Camera Bullet High Performance 4MP DarkFighter 2.8-12mm HikVision",
                            FovDiagonal = "67°–3°",
                            FovHorizontal = "57°–2.6°",
                            FovVertical = "33°–1.5°",
                            IrRange = "100m",
                            LensSize = "2.8-12mm",
                            LensType = "Motorised Varifocal",
                            ModelNumber = "DS-2CD7A47G0-XZHSY",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$900–$1200",
                            Range = "100m",
                            Resolution = "4MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 8,
                            Aperture = "F2.0",
                            Brand = "HikVision",
                            Description = "Camera Outdoor Dome 2MP 120db WDR IP67 Fixed Lens 30m IR 2.8mm HikVision",
                            FovDiagonal = "135°–102°",
                            FovHorizontal = "114°–86°",
                            FovVertical = "62°–46°",
                            IrRange = "30m",
                            LensSize = "2.8mm",
                            LensType = "Fixed Focal Lens",
                            ModelNumber = "DS-2CD2123G2-I",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$120–$180",
                            Range = "30m",
                            Resolution = "2MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 9,
                            Aperture = "F1.6",
                            Brand = "HikVision",
                            Description = "Camera Dome 2MP PTZ PoE IP66 4x Optical Zoom HikVision",
                            FovDiagonal = "122.6°-37.8",
                            FovHorizontal = "103.4°–33°",
                            FovVertical = "53.8°-18.9°",
                            IrRange = "30m",
                            LensSize = "4x Optical Zoom",
                            LensType = "PTZ",
                            ModelNumber = "DS-2DE3204W-DE",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$350–$500",
                            Range = "30m",
                            Resolution = "2MP",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 10,
                            Aperture = "F1.6",
                            Brand = "HikVision",
                            Description = "Camera Dome 6MP WDR Smart 2.8mm H.265 120dB (C)(0-STD",
                            FovDiagonal = "128°–101°",
                            FovHorizontal = "99°–80°",
                            FovVertical = "61°–51°",
                            IrRange = "30m",
                            LensSize = "2.8mm",
                            LensType = "Fixed Focal Lens",
                            ModelNumber = "DS-2CD2166G2-I",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$260–$340",
                            Range = "30m",
                            Resolution = "6MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 11,
                            Aperture = "F1.5",
                            Brand = "HikVision",
                            Description = "Camera PTZ 4MP 25x Dome Hikvision",
                            FovDiagonal = "60.5°-3°",
                            FovHorizontal = "57°–2.6°",
                            FovVertical = "30.6°-1.5°",
                            IrRange = "50m",
                            LensSize = "25x Optical Zoom",
                            LensType = "PTZ",
                            ModelNumber = "DS-2DE4A425IWG-E",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$900–$1200",
                            Range = "50m",
                            Resolution = "4MP",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 12,
                            Aperture = "F1.4",
                            Brand = "HikVision",
                            Description = "Camera - HIKVision 4MP Dome DeepinView Moto Varifocal 2.8- 12mm IK10",
                            FovDiagonal = "127°–52°",
                            FovHorizontal = "108°–46°",
                            FovVertical = "58°–26°",
                            IrRange = "80m",
                            LensSize = "2.8-12mm",
                            LensType = "Motorised Varifocal",
                            ModelNumber = "IDS-2CD7146G0-IZHSY",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$650–$850",
                            Range = "80m",
                            Resolution = "4MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 13,
                            Aperture = "F1.6",
                            Brand = "HikVision",
                            Description = "Camera - Hikvision 8 MP Smart Hybrid Light with ColorVu Mini Dome 2.8mm",
                            FovDiagonal = "120°",
                            FovHorizontal = "102°",
                            FovVertical = "55°",
                            IrRange = "30m",
                            LensSize = "2.8mm",
                            LensType = "Fixed Focal Lens",
                            ModelNumber = "DS-2CD2187G2H-LISU",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$260–$340",
                            Range = "30m",
                            Resolution = "8MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 14,
                            Aperture = "F1.6",
                            Brand = "HikVision",
                            Description = "Camera-Hikvision 4MP 4XOutdoor IR Wi-Fi Mini Dome PTZ DS-2DE2A404IW-DE3/W(S6)",
                            FovDiagonal = "115.13°-36.32°",
                            FovHorizontal = "98°–30°",
                            FovVertical = "51.16°-17.8°",
                            IrRange = "50m",
                            LensSize = "4x Optical Zoom",
                            LensType = "PTZ",
                            ModelNumber = "DS-2DE2A404IW-DE3/W",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$450–$650",
                            Range = "50m",
                            Resolution = "4MP",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 15,
                            Aperture = "F1.5",
                            Brand = "HikVision",
                            Description = "Camera-HikVision 2.8mm Panoram Dome 32x PTZ TandemVu Camera",
                            FovDiagonal = "",
                            FovHorizontal = "57°–2.6°",
                            FovVertical = "",
                            IrRange = "150m",
                            LensSize = "2.8mm",
                            LensType = "PTZ",
                            ModelNumber = "DS-2SE7C432MWG-EB/26",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$1800–$2400",
                            Range = "150m",
                            Resolution = "4MP",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 16,
                            Aperture = "F1.6",
                            Brand = "HikVision",
                            Description = "Dome Camera 5MP 2.8-12mm Varifocal H.265+ IP67 IK10 HikVision (2.8-12mm)(C)(O-STD)",
                            FovDiagonal = "128°–35°",
                            FovHorizontal = "99°–30°",
                            FovVertical = "61°–17°",
                            IrRange = "40m",
                            LensSize = "2.8-12mm",
                            LensType = "Motorised Varifocal",
                            ModelNumber = "DS-2CD2766G2-IZS",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$350–$500",
                            Range = "40m",
                            Resolution = "5MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 17,
                            Aperture = "F2.0",
                            Brand = "HikVision",
                            Description = "Camera FishEye 5MP H.265 Indoor 20M IR EasyIP3.0 HikVision",
                            FovDiagonal = "",
                            FovHorizontal = "360°",
                            FovVertical = "",
                            IrRange = "10m",
                            LensSize = "1.05mm",
                            LensType = "Fisheye",
                            ModelNumber = "DS-2CD2955FWD-I",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$250–$350",
                            Range = "20m",
                            Resolution = "5MP",
                            Type = "Fisheye"
                        },
                        new
                        {
                            Id = 18,
                            Aperture = "F2.0",
                            Brand = "HikVision",
                            Description = "Camera - Hikvision 6 MP Deepin View Fisheye Network 1.16 mm DS-2CD6365G1-IVS(1.16mm)",
                            FovDiagonal = "",
                            FovHorizontal = "360°",
                            FovVertical = "",
                            IrRange = "15m",
                            LensSize = "1.16mm",
                            LensType = "Fisheye",
                            ModelNumber = "DS-2CD6365G1-IVS",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$450–$650",
                            Range = "15m",
                            Resolution = "6MP",
                            Type = "Fisheye"
                        },
                        new
                        {
                            Id = 19,
                            Aperture = "F2.0",
                            Brand = "HikVision",
                            Description = "Camera - 5MP Fixed Fisheye Network",
                            FovDiagonal = "",
                            FovHorizontal = "360°",
                            FovVertical = "",
                            IrRange = "10m",
                            LensSize = "1.05mm",
                            LensType = "Fisheye",
                            ModelNumber = "DS-2CD2955G0-ISU",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$250–$350",
                            Range = "10m",
                            Resolution = "5MP",
                            Type = "Fisheye"
                        },
                        new
                        {
                            Id = 20,
                            Aperture = "F1.6",
                            Brand = "PTZOptics",
                            Description = "Camera PTZOptics Auto Tracking 20X Opt Zoom 1080p",
                            FovDiagonal = "",
                            FovHorizontal = "59°–2.3°",
                            FovVertical = "",
                            IrRange = "100m",
                            LensSize = "20x Optical Zoom",
                            LensType = "PTZ",
                            ModelNumber = "HUD-PT20X-SE-GY-G3",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$1200–$1600",
                            Range = "100m",
                            Resolution = "1080p",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 21,
                            Aperture = "F1.5",
                            Brand = "HikVision",
                            Description = "Camera PTZ 5MP 30x Zoom 150m IR IP66 Pendant HikVision",
                            FovDiagonal = "",
                            FovHorizontal = "60°–2.3°",
                            FovVertical = "",
                            IrRange = "200m",
                            LensSize = "30x Optical Zoom",
                            LensType = "PTZ",
                            ModelNumber = "DS-2DE7530IW-AE",
                            OperatingTemp = "–30°C to 60°C",
                            Price = "$2500–$3200",
                            Range = "150m",
                            Resolution = "5MP",
                            Type = "PTZ"
                        });
                });

            modelBuilder.Entity("Backend.Models.CameraPlacement", b =>
                {
                    b.Property<int>("PlacementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlacementID"));

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<int>("FloorID")
                        .HasColumnType("int");

                    b.Property<int?>("FloorLayoutFloorID")
                        .HasColumnType("int");

                    b.Property<double>("Rotation")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("PlacementID");

                    b.HasIndex("FloorLayoutFloorID");

                    b.ToTable("CameraPlacemens");
                });

            modelBuilder.Entity("Backend.Models.FloorLayout", b =>
                {
                    b.Property<int>("FloorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FloorID"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("ImageContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Layer")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("FloorID");

                    b.HasIndex("ProjectID");

                    b.ToTable("FloorLayouts");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProjectID");

                    b.HasIndex("UserID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.CameraPlacement", b =>
                {
                    b.HasOne("Backend.Models.FloorLayout", "FloorLayout")
                        .WithMany()
                        .HasForeignKey("FloorLayoutFloorID");

                    b.Navigation("FloorLayout");
                });

            modelBuilder.Entity("Backend.Models.FloorLayout", b =>
                {
                    b.HasOne("Backend.Models.Project", "Project")
                        .WithMany("FloorLayouts")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.Navigation("FloorLayouts");
                });
#pragma warning restore 612, 618
        }
    }
}
