// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LensSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "HikVision",
                            Description = "Camera Bullet 8MP V-Focus HikVision",
                            LensSize = "Varifocal",
                            ModelNumber = "DS-2CD2685G1-IZS",
                            Range = "",
                            Resolution = "8MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "HikVision",
                            Description = "Camera 4MP Mini Bullet 40m IR IP67 2.8mm HIKVision",
                            LensSize = "2.8mm",
                            ModelNumber = "DS-2CD2046G2-I",
                            Range = "40m",
                            Resolution = "4MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "HikVision",
                            Description = "Camera Bullet Single 2MP 30m WiFi IR IP66 2.8mm",
                            LensSize = "2.8mm",
                            ModelNumber = "DS-2CD2021G1-IDW1",
                            Range = "30m",
                            Resolution = "2MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "HikVision",
                            Description = "Camera Bullet 6MP 50m IR 2.8mm EXIR H.265 120dB WDR IP67",
                            LensSize = "2.8mm",
                            ModelNumber = "DS-2CD2T65G1-I8",
                            Range = "50m",
                            Resolution = "6MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "HikVision",
                            Description = "Camera HIKVision 4K AcuSense Strobe Light Audible Warning Varifocal Bullet",
                            LensSize = "Varifocal",
                            ModelNumber = "DS-2CD2686G2-IZSU/SL",
                            Range = "",
                            Resolution = "8MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "HikVision",
                            Description = "Camera Hikvision 4MP Deepin View ANPR Moto VF Bullet 8-32mm",
                            LensSize = "8-32mm",
                            ModelNumber = "IDS-2CD7A46G0/P-IZHS",
                            Range = "8-32m",
                            Resolution = "4MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "HikVision",
                            Description = "Camera Bullet High Performance 4MP DarkFighter 2.8-12mm HikVision",
                            LensSize = "2.8-12mm",
                            ModelNumber = "DS-2CD7A47G0-XZHSY",
                            Range = "",
                            Resolution = "4MP",
                            Type = "Bullet"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "HikVision",
                            Description = "Camera Outdoor Dome 2MP 120dB WDR IP67 Fixed Lens 30m IR 2.8mm HikVision",
                            LensSize = "2.8mm",
                            ModelNumber = "DS-2CD2123G2-I",
                            Range = "30m",
                            Resolution = "2MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "HikVision",
                            Description = "Camera Dome 2MP PTZ PoE IP66 4x Optical Zoom HikVision",
                            LensSize = "4x Optical Zoom",
                            ModelNumber = "DS-2DE3204W-DE",
                            Range = "",
                            Resolution = "2MP",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "HikVision",
                            Description = "Camera Dome 6MP WDR Smart 2.8mm H.265 120dB",
                            LensSize = "2.8mm",
                            ModelNumber = "DS-2CD2166G2-I",
                            Range = "",
                            Resolution = "6MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "HikVision",
                            Description = "Camera PTZ 4MP 25x Dome Hikvision",
                            LensSize = "25x Optical Zoom",
                            ModelNumber = "DS-2DE4A425IWG-E",
                            Range = "",
                            Resolution = "4MP",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "HikVision",
                            Description = "Camera HIKVision 4MP Dome DeepinView Moto Varifocal 2.8-12mm IK10",
                            LensSize = "2.8-12mm",
                            ModelNumber = "IDS-2CD7146G0-IZHSY",
                            Range = "",
                            Resolution = "4MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "HikVision",
                            Description = "Camera Hikvision 8MP Smart Hybrid Light with ColorVu Mini Dome 2.8mm",
                            LensSize = "2.8mm",
                            ModelNumber = "DS-2CD2187G2H-LISU",
                            Range = "",
                            Resolution = "8MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "HikVision",
                            Description = "Camera Hikvision 4MP 4X Outdoor IR Wi-Fi Mini Dome PTZ",
                            LensSize = "4x Optical Zoom",
                            ModelNumber = "DS-2DE2A404IW-DE3/W",
                            Range = "",
                            Resolution = "4MP",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "HikVision",
                            Description = "Camera HikVision 2.8mm Panoramic Dome 32x PTZ TandemVu Camera",
                            LensSize = "2.8mm",
                            ModelNumber = "DS-2SE7C432MWG-EB/26",
                            Range = "",
                            Resolution = "4MP",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "HikVision",
                            Description = "Dome Camera 5MP 2.8-12mm Varifocal H.265+ IP67 IK10 HikVision",
                            LensSize = "2.8-12mm",
                            ModelNumber = "DS-2CD2766G2-IZS",
                            Range = "",
                            Resolution = "5MP",
                            Type = "Dome"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "HikVision",
                            Description = "Camera FishEye 5MP H.265 Indoor 20m IR EasyIP3.0 HikVision",
                            LensSize = "1.05mm",
                            ModelNumber = "DS-2CD2955FWD-I",
                            Range = "20m",
                            Resolution = "5MP",
                            Type = "Fisheye"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "HikVision",
                            Description = "Camera Hikvision 6MP Deepin View Fisheye Network 1.16mm",
                            LensSize = "1.16mm",
                            ModelNumber = "DS-2CD6365G1-IVS",
                            Range = "",
                            Resolution = "6MP",
                            Type = "Fisheye"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "HikVision",
                            Description = "Camera 5MP Fixed Fisheye Network",
                            LensSize = "1.05mm",
                            ModelNumber = "DS-2CD2955G0-ISU",
                            Range = "",
                            Resolution = "5MP",
                            Type = "Fisheye"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "PTZOptics",
                            Description = "Camera PTZOptics Auto Tracking 20X Opt Zoom 1080p",
                            LensSize = "20x Optical Zoom",
                            ModelNumber = "HUD-PT20X-SE-GY-G3",
                            Range = "",
                            Resolution = "1080p",
                            Type = "PTZ"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "HikVision",
                            Description = "Camera PTZ 5MP 30x Zoom 150m IR IP66 Pendant HikVision",
                            LensSize = "30x Optical Zoom",
                            ModelNumber = "DS-2DE7530IW-AE",
                            Range = "150m",
                            Resolution = "5MP",
                            Type = "PTZ"
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
