namespace Backend.Models
{
    // this class represents a camera in the database
    // each property here matches a column in the Cameras table
    public class Camera
    {
        // unique identifier for each camera, automatically generated by the database
        public int Id { get; set; }

        // the model number of the camera e.g. DS-2CD2685G1-IZS
        public string ModelNumber { get; set; } = string.Empty;

        // a short description of the camera including its key features
        public string Description { get; set; } = string.Empty;

        // the brand/manufacturer of the camera e.g. HikVision
        public string Brand { get; set; } = string.Empty;

        // the type of camera e.g. Bullet, Dome, PTZ, Fisheye
        public string Type { get; set; } = string.Empty;

        // the resolution of the camera e.g. 2MP, 4MP, 8MP
        public string Resolution { get; set; } = string.Empty;

        // the infrared range of the camera e.g. 30m, 50m
        // some cameras may not have a range so this can be empty
        public string Range { get; set; } = string.Empty;

        // the lens size of the camera e.g. 2.8mm, Varifocal
        public string LensSize { get; set; } = string.Empty;
    }
}