namespace Backend.Models
{
    // this class represents a project in the database
    // each property matches a column in the Projects table
    public class Project
    {
        // unique identifier for each project, automatically generated by the database
        public int ProjectID { get; set; }

        // the id of the user who created the project
        // links to the Users table (Foreign Key)
        public int UserID { get; set; }

        // the id of the client the project is for
        // links to the Clients table (Foreign Key)
        public int ClientID { get; set; }

        // the name/title of the project
        public string Title { get; set; } = string.Empty;

        // the address of the project location
        public string Address { get; set; } = string.Empty;

        // a description of the project
        public string Description { get; set; } = string.Empty;

        // navigation property - a project can have many floor images
        public List<FloorLayout> FloorLayouts { get; set; } = new();

        // navigation property - links to the User who created the project
        public User? User { get; set; }
    }
}