using System.ComponentModel.DataAnnotations;

namespace Backend.Models
{
    // this class represents a user in the database
    // each property here matches a column in the Users table
    public class User
    {
        // unique identifier for each user, automatically generated by the database
        public int Id { get; set; }

        // the username chosen by the user when registering
        // [Required] means this field cannot be empty
        [Required]
        public string Username { get; set; } = string.Empty;

        // the email address of the user
        // [Required] means this field cannot be empty
        // this is also used to log in
        [Required]
        public string Email { get; set; } = string.Empty;

        // the hashed version of the user's password
        // [Required] means this field cannot be empty
        // the actual password is never stored, only the hashed version
        [Required]
        public string PasswordHash { get; set; } = string.Empty;
    }
}